VALID_KEYS_TEXT = (
    "VALID KEYS REFERENCE:\n"
    "Standard: a-z, 0-9, SPACE, TAB, ENTER, ESCAPE, BACKSPACE\n"
    "Modifiers: SHIFT, CTRL, ALT, CAPSLOCK, COMMAND, PAUSE\n"
    "Symbols: SEMICOLON, BACKSLASH\n"
    "Navigation: INS, DEL, HOME, END, PGUP, PGDN\n"
    "Arrows: UPARROW, DOWNARROW, LEFTARROW, RIGHTARROW\n"
    "Function: F1-F24\n"
    "Mouse: MOUSE1-MOUSE9, MWHEELUP, MWHEELDOWN\n"
    "Keypad: KP_HOME, KP_END, KP_PGUP, KP_PGDN, KP_DEL, KP_INS\n"
    "KP_UPARROW, KP_DOWNARROW, KP_LEFTARROW, KP_RIGHTARROW\n"
    "KP_5, KP_ENTER, KP_PLUS, KP_MINUS, KP_STAR, KP_SLASH\n"
    "KP_EQUALS, KP_NUMLOCK\n"
    "Joystick: JOY1-JOY32"
)

CROSSHAIR_INFO_TEXT = (
    "CROSSHAIR STYLES (0-20):\n"
    "0 = No crosshair\n"
    "1 = Cross\n"
    "2 = Exploded cross\n"
    "3 = Disk + dot\n"
    "4 = Circle + dot\n"
    "5 = Big dot\n"
    "6 = Circle + cross\n"
    "7 = Big exploded cross\n"
    "8 = Big exploded cross + dot\n"
    "9 = Side curves + dot\n"
    "10 = Circle + dot\n"
    "11 = Cross w/ black outline\n"
    "12 = Exploded cross w/ black outline\n"
    "13 = Disk + dot w/ black outline\n"
    "14 = Circle + dot w/ black outline\n"
    "15 = Dot w/ black outline\n"
    "16 = Circle + cross w/ black outline\n"
    "17 = Mirrored L w/ black outline\n"
    "18 = Cross + dot w/ black outlines\n"
    "19 = Side curves + dot w/ black outline\n"
    "20 = Circle + exploded cross + dot"
)