import re
from pathlib import Path
from src.logic.settings import (
    VIDEO_SETTINGS,
    MOUSE_SETTINGS,
    AUDIO_SETTINGS,
    HUD_SETTINGS,
    PLAYER_SETTINGS,
    WEAPON_SETTINGS,
    KEYBIND_SETTINGS
)

ALL_SETTINGS_GROUPS = [
    VIDEO_SETTINGS,
    MOUSE_SETTINGS,
    AUDIO_SETTINGS,
    HUD_SETTINGS,
    PLAYER_SETTINGS,
    WEAPON_SETTINGS,
    KEYBIND_SETTINGS
]


def load_existing_config(cfg_path: Path):
    """
    Reads the existing gui.cfg file and updates the 'value' key
    in the global settings dictionaries for any matching commands found.
    """
    cfg_path = Path(cfg_path)
    if not cfg_path.exists():
        return

    with open(cfg_path, "r") as f:
        content = f.read()

    seta_matches = re.findall(r'seta\s+(\w+)\s+"(.*?)"', content)
    for command, found_value in seta_matches:
        for settings_dict in ALL_SETTINGS_GROUPS:
            # Skip keybinds here, they are handled below
            if settings_dict is KEYBIND_SETTINGS:
                continue

            if command in settings_dict:
                settings_dict[command]["value"] = found_value
                break


    bind_matches = re.findall(r'bind\s+(\S+)\s+"(.*?)"', content)

    for found_key, found_action in bind_matches:
        clean_key = found_key.strip('"')

        if found_action in KEYBIND_SETTINGS:
            KEYBIND_SETTINGS[found_action]["value"] = clean_key

def save_current_config(cfg_path: Path, autoexec_path: Path):
    """
    Wipes the gui.cfg file and rewrites it using ONLY the values
    from the dictionaries that are NOT None.
    """
    lines = [
        "// CPMA GUI Configuration File",
        "// Generated automatically by CPMA Config Editor",
        "// Do not edit this file manually; use the GUI instead.",
        ""
    ]

    append_to_autoexec(autoexec_path)

    for settings_dict in ALL_SETTINGS_GROUPS:
        for command, data in settings_dict.items():
            val = data.get("value")

            if val is not None:
                if settings_dict is KEYBIND_SETTINGS:
                    lines.append(f'bind {val} "{command}"')
                else:
                    lines.append(f'seta {command} "{val}"')

    with open(cfg_path, "w") as f:
        f.write("\n".join(lines))

def append_to_autoexec(autoexec_path: Path):
    with open(autoexec_path, "r") as f:
        content = f.read()

    if "exec gui.cfg" not in content.lower():
        with open(autoexec_path, "a") as f:
            f.write("\n// Load the GUI config\n")
            f.write("exec gui.cfg\n")