import re
from pathlib import Path
from src.settings import (
    VIDEO_SETTINGS,
    MOUSE_SETTINGS,
    AUDIO_SETTINGS,
    HUD_SETTINGS,
    PLAYER_SETTINGS,
    WEAPON_SETTINGS
)

ALL_SETTINGS_GROUPS = [
    VIDEO_SETTINGS,
    MOUSE_SETTINGS,
    AUDIO_SETTINGS,
    HUD_SETTINGS,
    PLAYER_SETTINGS,
    WEAPON_SETTINGS
]


def load_existing_config(cfg_path: Path):
    """
    Reads the existing gui.cfg file and updates the 'value' key
    in the global settings dictionaries for any matching commands found.
    """
    if not cfg_path.exists():
        return

    try:
        with open(cfg_path, "r") as f:
            content = f.read()

        # Regex explanation:
        # seta   -> looks for the literal word 'seta'
        # \s+    -> followed by one or more spaces
        # (\w+)  -> captures the command name (Group 1)
        # \s+    -> followed by spaces
        # "(.*?)"-> captures the value inside double quotes (Group 2)
        matches = re.findall(r'seta\s+(\w+)\s+"(.*?)"', content)

        for command, found_value in matches:
            # We found a command in the file (e.g., 'm_speed' with value '2.5')
            # Now we must find which dictionary it belongs to and update it.
            found_in_dict = False

            for settings_dict in ALL_SETTINGS_GROUPS:
                if command in settings_dict:
                    # Update the dictionary value
                    settings_dict[command]["value"] = found_value
                    found_in_dict = True
                    break

            # Optional: You could log if a command was found in the file
            # but not in your dictionary (meaning it might be obsolete).

    except Exception as e:
        print(f"Error loading config: {e}")


def save_current_config(cfg_path: Path):
    """
    Wipes the gui.cfg file and rewrites it using ONLY the values
    from the dictionaries that are NOT None.
    """
    lines = [
        "// CPMA GUI Configuration File",
        "// Generated automatically by CPMA Config Editor",
        "// Do not edit this file manually; use the GUI instead.",
        ""
    ]

    # Iterate through every dictionary group
    for settings_dict in ALL_SETTINGS_GROUPS:
        for command, data in settings_dict.items():

            val = data.get("value")

            # CORE LOGIC: Only write if the value is actively set (not None)
            if val is not None:
                # Format: seta command "value"
                lines.append(f'seta {command} "{val}"')

    # Ensure the parent directory exists (just in case)
    if not cfg_path.parent.exists():
        cfg_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        with open(cfg_path, "w") as f:
            f.write("\n".join(lines))
        print(f"Successfully saved configuration to {cfg_path}")

    except Exception as e:
        print(f"Error saving config: {e}")